name: Playwright Tests Nightly
on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
          
      - name: Clean old reports
        run: |
          rm -rf test-results/custom-report/
          rm -rf playwright-report/
          
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_HEADLESS: true
        run: npx playwright test HomepageTest.spec.ts RegistrationPageTest.spec.ts
        
      - name: List test results
        if: always()
        run: ls -la test-results/custom-report/
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-results/custom-report/
        
  deploy:
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clean deployment directory
        run: |
          rm -rf ./*
          
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-report
          
      - name: List files
        run: ls -la
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send Slack notification
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "🤖 *Autonomous Test Report*\n\n*Status*: ${{ job.status }}\n*Workflow*: ${{ github.workflow }}\n*Run*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}>\n*Pages URL*: ${{ steps.deployment.outputs.page_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/triggers/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"
          SLACK_WEBHOOK_TYPE: "INCOMING_WEBHOOK"
